// <auto-generated />
namespace BlueBadge.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class udae : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(udae));
        
        string IMigrationMetadata.Id
        {
            get { return "201902222221048_udae"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
